"""initial schema

Revision ID: b43d40e8b233
Revises: 
Create Date: 2026-03-02 10:49:21.947504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43d40e8b233'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('science_parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('land', sa.String(length=100), nullable=False),
    sa.Column('stadt', sa.String(length=100), nullable=False),
    sa.Column('gruendungsjahr', sa.Integer(), nullable=True),
    sa.Column('bisherige_kooperation', sa.String(length=20), nullable=True),
    sa.Column('datum', sa.String(length=10), nullable=True),
    sa.Column('themen', sa.JSON(), nullable=True),
    sa.Column('bemerkungen', sa.Text(), nullable=True),
    sa.Column('ansprechpartner', sa.String(length=255), nullable=True),
    sa.Column('kontaktdetails', sa.Text(), nullable=True),
    sa.Column('webpraesenz', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("bisherige_kooperation IN ('Keine', 'Geplant', 'Aktiv', 'Abgeschlossen')", name='ck_science_parks_kooperation'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('readonly', 'readwrite', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('universitaeten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('science_park_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('standort', sa.String(length=255), nullable=True),
    sa.Column('forschungsschwerpunkte', sa.JSON(), nullable=True),
    sa.Column('ansprechpartner', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['science_park_id'], ['science_parks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('science_park_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('universitaeten')
    op.drop_table('users')
    op.drop_table('science_parks')
    # ### end Alembic commands ###
